[build-system]
requires = ["setuptools", "wheel"]

[project]
name="clickup-apy"
version="0.1.0"
description="Python ClickUp API Wrapper"
authors=[
    { name: "James Richmond" }
]
dependencies=["requests"]